project:
  type: website

website:
  title: "Movie Rankings"
  site-url: http://ianranksmovies.netlify.app
  navbar:
    right:
      - text: Blog
        href: blog.qmd
      - text: About
        href: about.qmd
      - icon: Github
        href: https://github.com/ianrmcdonald/bfi_poll
      - icon: Twitter
        href: https://twitter.com/ianrmcdonald
      
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

