project:
  type: website

website:
  title: "Movie Rankings"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ianrmcdonald/bfi_poll
      - icon: twitter
        href: https://twitter.com/ianrmcdonald
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

